"""Profiles missingness per dataset against the canonical 38-province set and writes
docs/missing_data_report.md. Reports only -- never imputes, never drops a real
province row to "fix" the count.

Usage: python -m src.cleaning.profile_missing
"""

import logging

import pandas as pd

from src.cleaning.standardize import standardize_dataset
from src.utils.config import DOCS_DIR, PROVINCE_LOOKUP_PATH

log = logging.getLogger(__name__)

REPORT_PATH = DOCS_DIR / "missing_data_report.md"

DATASET_VALUE_COLUMNS = {
    "poverty": ["poverty_rate"],
    "ipm": ["ipm"],
    "population": ["population"],
    "education": ["participation_rate"],
    "expenditure": ["expenditure_per_capita"],
    "stunting": ["stunting_rate", "stunting_category"],
}

# Recommended missing-value policy per dataset, decided here rather than left implicit.
# "leave_null" means: the merged table carries a null for that province/indicator,
# never imputed. No dataset in this project currently warrants interpolation or
# carry-forward, because every gap found is either a real BPS publication gap
# (population, education) or simply absent metadata -- not a transient data-entry hole.
RECOMMENDED_POLICY = {
    "poverty": "leave_null (no gaps found)",
    "ipm": "leave_null (no gaps found)",
    "population": "leave_null -- BPS has not republished this series for the 4 provinces created by the 2022 Papua split; do not estimate by splitting the old combined figure",
    "education": "leave_null -- same reason as population",
    "expenditure": "leave_null (no gaps found)",
    "stunting": "leave_null (no gaps found)",
}


def profile_dataset(slug: str, value_columns: list[str]) -> dict:
    canonical = set(pd.read_csv(PROVINCE_LOOKUP_PATH)["canonical_name"].unique())
    df, report = standardize_dataset(slug, value_columns)
    present = set(df["province"].unique())
    missing = sorted(canonical - present)
    return {
        "dataset": slug,
        "rows_in": report.rows_in,
        "rows_dropped_non_province": report.rows_dropped_non_province,
        "rows_dropped_exact_duplicate": report.rows_dropped_exact_duplicate,
        "inconsistent_keys": report.inconsistent_keys,
        "n_provinces_present": len(present),
        "n_provinces_missing": len(missing),
        "missing_provinces": missing,
        "years_present": sorted(df["year"].unique().tolist()),
    }


def render(profiles: list[dict]) -> str:
    lines = [
        "# Missing Data Report",
        "",
        "Generated by `python -m src.cleaning.profile_missing`. Profiles each cleaned "
        "dataset against the canonical 38-province set. No value here is ever imputed "
        "-- a missing province means BPS has not published that series for it yet.",
        "",
        "| Dataset | Provinces present | Provinces missing | Years available | Recommended policy |",
        "|---|---|---|---|---|",
    ]
    for p in profiles:
        lines.append(
            f"| {p['dataset']} | {p['n_provinces_present']}/38 | {p['n_provinces_missing']} | "
            f"{p['years_present']} | {RECOMMENDED_POLICY[p['dataset']]} |"
        )

    lines += ["", "## Detail", ""]
    for p in profiles:
        lines.append(f"### {p['dataset']}")
        lines.append("")
        lines.append(f"- Raw rows ingested: {p['rows_in']}")
        lines.append(f"- Dropped as non-province aggregate rows: {p['rows_dropped_non_province']}")
        lines.append(f"- Dropped as exact duplicates: {p['rows_dropped_exact_duplicate']}")
        lines.append(f"- Inconsistent (province, year) keys (same key, conflicting values): {p['inconsistent_keys'] or 'none'}")
        if p["missing_provinces"]:
            lines.append(f"- Missing provinces: {', '.join(p['missing_provinces'])}")
        else:
            lines.append("- Missing provinces: none")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    logging.basicConfig(level=logging.INFO)
    profiles = [profile_dataset(slug, cols) for slug, cols in DATASET_VALUE_COLUMNS.items()]
    REPORT_PATH.write_text(render(profiles))
    log.info("Wrote %s", REPORT_PATH)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
